[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd %appdata%"
desc = "Go to %appdata%"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd C:"
desc = "Switch to C drive"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd D:"
desc = "Switch to D drive"

[[mgr.prepend_keymap]]
on   = [ "g", "e" ]
run  = "cd E:"
desc = "Switch to E drive"
